---
# tasks file for addWebUids

- name: Add user group first before adding user.
  group: name={{ item.key }} gid={{ item.value.uid }} state=present
  with_dict: users

- name: Add users from vars file using dict
  user: name={{ item.key }} password={{ item.value.password }} shell={{ item.value.shell }} comment="{{ item.value.comment }}" uid={{ item.value.uid }} group={{ item.value.group }} groups={{ item.value.groups }} createhome={{ item.value.createhome }} state={{ item.value.state }}
  with_dict: users

#- name: Send email.
#  local_action: mail host=smtp.co.ihc.com subject="Ansible User Add" body="{{ ansible_hostname }} user {{ item.key }} added. Please login to change your password. The initial password is chang3m3" from="ramon.gonzalez@imail.org" to="ramon.gonzalez@imail.org" charset=utf8
#  with_dict: users 
# ignore_errors: true

#- name: Send hipchat message.
#  hipchat: api="https://hipchat.co.ihc.com/v2/room/200/notification" token=V6o6hkFwteMCU7PycKFm9H8mQtZ1eYYfPbP2xJD0 room=notify msg="{{ ansible_hostname }} user {{ item.key }} added."
#  with_dict: users
#  ignore_errors: true
