---
- hosts: all

  vars:
    - website_dir: /var/www/oursite.dev/web

# roles section added when tasks and handlers moved to roles/apache/tasks,handlers, main.yml etc 
  roles:
    - apache

# tasks moved to tasks/main.yml    
  tasks:
    - name: Install Apache
      apt: pkg=apache2 state=installed update_cache=true
      notify:
        - start apache2

    - name: Create website directory
      file: dest={{  website_dir  }} mode=775 state=directory owner=www-data group=www-data
      notify:
        - restart apache2

# handlers moved to handlers/main.yml

  handlers:
    - name: start apache
      service: name=apache2 state=started

    - name: restart apache
      service: name=apache2 state=restarted          